### ISSUE TITLE
Link to Etherscan goes to main page rather than wallet address

### ISSUE THREAD

**Issue by Yazan24** [jibrelnetwork/jwallet-web#118]
<img width="244" alt="screen shot 2017-11-22 at 7 21 46 pm" src="https://user-images.githubusercontent.com/25491050/33155012-aee150ba-cfba-11e7-8ecf-c9cd61480f2d.png">

Link should go to https://etherscan.io/address/[WALLETADDRESS]

**Comment by IViol** [comment]
FIxed in 9f0a56839ffb4621d1ec8ddc5c340484779640ce
