### ISSUE TITLE
Trx detail drawer status same on all token views

### ISSUE THREAD

**Issue by Yazan24** [jibrelnetwork/jwallet-web#123]
Status of transaction details window (open or closed) is same across all token windows 

i.e. if I expand a transaction in one token (e.g. Ethereum) and switch to another (e.g. Golem Network Token), the same transaction is open in that window. If I close it, it closes across windows.

They share the same status, needs to be split.

**Comment by IViol** [comment]
Fixed in b89cedd56bf5c9536bc5ca5fc42400c708f533da
