### ISSUE TITLE
Send Drop-down should only show active tokens

### ISSUE THREAD

**Issue by Yazan24** [jibrelnetwork/jwallet-web#124]
Send Drop-down should only show active tokens - it currently shows all available tokens

<img width="564" alt="screen shot 2017-11-24 at 11 25 19 pm" src="https://user-images.githubusercontent.com/25491050/33227336-1523acdc-d16f-11e7-96b3-c7f419922a65.png">

**Comment by IViol** [comment]
Updated in e0432c7667a0c888e2cdd838bfca783740e72863
