### ISSUE TITLE
Rename Custom options in Send window to Gas Parameters

### ISSUE THREAD

**Issue by Yazan24** [jibrelnetwork/jwallet-web#125]
Lets rename to Custom Gas

<img width="489" alt="screen shot 2017-11-24 at 11 27 14 pm" src="https://user-images.githubusercontent.com/25491050/33227393-e9ba62d8-d16f-11e7-87c8-e626a0682e2b.png">

And show the default values in the greyed out text
e.g.

Limit (21,000 Gas)
Price (1 Gwei)

Format text in brackets as regular font weight

**Comment by IViol** [comment]
Updated in ac9f970d9b12faf5b8d7dcf30b96a9e651e7a56d
