### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by mezrin** [jibrelnetwork/jwallet-web#133]
we have a translation to Korean

need to integrate it into the app

[jwallet translation(kr).docx](https://github.com/jibrelnetwork/jwallet-web/files/1515800/jwallet.translation.kr.docx)
[jwallet website (1) (1).docx](https://github.com/jibrelnetwork/jwallet-web/files/1515801/jwallet.website.1.1.docx)

**Comment by martinin** [comment]
https://xd.adobe.com/view/eb712d49-a329-4ac7-af5d-9e9442d67b4f/screen/3582f6e9-b6ce-46d9-a958-da745e933cf5/1-start

Поповер аналогичный остальным

**Comment by IViol** [comment]
Resolved in 6365beb01a35d9360c966c4f306f9e0443f722b3
