### ISSUE TITLE
Untrusted / Public Device feature

### ISSUE THREAD

**Issue by Yazan24** [jibrelnetwork/jwallet-web#140]
There should be the ability to only check the wallet once, without importing the key into memory - i.e. I am on a friends computer or at a coffee / internet shop.

I want to import my key, but clear it immediately when I close the browser window.

**Comment by IViol** [comment]
@Yazan24 it is possible, if you are opening jwallet in incognito tab/window

**Comment by Yazan24** [comment]
Of course :)

Is there anyway to have a clear keys - where you specifically delete the keys from the wallet? But not the full cache?
