### ISSUE TITLE
ETH Fee is Incorrect for incoming transaction

### ISSUE THREAD

**Issue by tarekayna** [jibrelnetwork/jwallet-web#146]
You are calculating the fee as: 
`      fee: ((cumulativeGasUsed * gasPrice) / (10 ** defaultDecimals)),`

Which results in an incorrect fee.

Etherscan calculates it as Gas Price * Gas Used By Transaction. (you can see this by inspecting the fee on etherscan transaction page).

Example:
https://etherscan.io/tx/0x6a89fc2d38b982cb320448be7d9ed4a227b127b3dbcc95678150f5232e546557

JWallet shows fee of 0.27616 ETH
Actual fee is 0.00101010147

**Comment by IViol** [comment]
@tarekayna 
Hey mate! Thank you for contribution and for your interest.
Your issue was solved in c10f535184fd1a029acfe6b3537ea5734e3ae220
