### ISSUE TITLE
Can't switch to another Digital Asset if the transactions are loading

### ISSUE THREAD

**Issue by tarekayna** [jibrelnetwork/jwallet-web#148]
Repro steps:
 - Open JWallet
 - Click on Bancor Network Token
 - While it is still loading, click on ETH

Expected: UI Switches to ETH and cancels the loading of BNT
Actual: UI is not responsive. When the BNT transactions load (which I have none), then the UI is responsive again.

**Comment by erohin** [comment]
fixed in jWallet Beta
