### ISSUE TITLE
Removing a key does not update the balance

### ISSUE THREAD

**Issue by tarekayna** [jibrelnetwork/jwallet-web#151]
Even after removing all keys, my balance still shows as 0.1 ETH
![image](https://user-images.githubusercontent.com/1313626/34083726-eaeb8900-e37d-11e7-93e2-84cd7eded6b5.png)

**Comment by mezrin** [comment]
Issue in the business logic

**Comment by DEVilishWAY** [comment]
This is also happening with the JNT jWallet. Seems removing the keys does not help at all. Also the balance shows but it labels 0 transactions, and will not allow any transfers. Using only as storage but should be a priority to not cause confusion.

**Comment by IViol** [comment]
Resolved by https://github.com/jibrelnetwork/jwallet-web/pull/188
