### ISSUE TITLE
Outgoing transaction disappears until it shows up on etherscan

### ISSUE THREAD

**Issue by tarekayna** [jibrelnetwork/jwallet-web#158]
When submitting an outgoing transaction, the modal closes and everything remains the same => total ETH , Transactions, etc... 

I would expect a pending outgoing transaction to show up on the transactions list and for jWallet to not allow me to submit another transaction whose value is > TOTAL - Pending Transaction.

**Comment by mezrin** [comment]
We know about this UX issue. Will be fixed in the new jWallet design
