### ISSUE TITLE
jWallet shows incorrect total balance of eth

### ISSUE THREAD

**Issue by tarekayna** [jibrelnetwork/jwallet-web#159]
jWallet shows a total balance of ETH of 0.05.

The actual balance on the address is 0.049559.

The reason is that jWallet is calculating the total as (TOTAL INCOMING - TOTAL OUTGOING) values. jWallet needs to deduct the fees from outgoing transactions in this calculation. Alternately you can check total from etherscan for the wallet address.

![97b2520a-80a0-4bf4-b1e3-96379083f78d](https://user-images.githubusercontent.com/1313626/34326220-7a19a71a-e8b0-11e7-892e-149dea7ff5be.jpg)
![26aad849-3507-4c46-ab8a-3af0d9e9ae68](https://user-images.githubusercontent.com/1313626/34326221-7a3e3418-e8b0-11e7-969a-141b75f51678.jpg)

**Comment by mezrin** [comment]
looks like rounding error. Will be fixed in the new version of jWallet

**Comment by erohin** [comment]
this because of math rounding. We are going to fix this UX issue in the jWallet Beta
