### ISSUE TITLE
Cropped bottom of text in mobile view for cards

### ISSUE THREAD

**Issue by Yazan24** [jibrelnetwork/jwallet-web#167]
<img width="178" alt="screen shot 2018-01-15 at 3 55 22 pm" src="https://user-images.githubusercontent.com/25491050/34961414-1003b7ee-fa0d-11e7-9197-aa9493eadf78.png">
<img width="112" alt="screen shot 2018-01-15 at 3 55 14 pm" src="https://user-images.githubusercontent.com/25491050/34961417-102dcebc-fa0d-11e7-8774-16e91b6e7da5.png">
<img width="316" alt="screen shot 2018-01-15 at 3 55 11 pm" src="https://user-images.githubusercontent.com/25491050/34961418-1057a03e-fa0d-11e7-8342-43354cf99d87.png">

Been a problem since day 1.

**Comment by mezrin** [comment]
should not appear in the new design

**Comment by IViol** [comment]
Fixed in 164e85383e5b84595d1bebb996f81a3904ce64f2
