### ISSUE TITLE
JIP-Wallet-6 Setup linter

### ISSUE THREAD

**Issue by mezrin** [jibrelnetwork/jwallet-web#171]
Create config for the linter, update code based on the linter warnings

**Comment by erohin** [comment]
NPM package with eslint config for all JS projects:
https://github.com/jibrelnetwork/eslint-config-jibrel

**Comment by erohin** [comment]
NPM package with stylelint config (RSCSS convention)
https://github.com/jibrelnetwork/stylelint-config-jibrel
