### ISSUE TITLE
Bug with the displaying of JNT license status

### ISSUE THREAD

**Issue by mezrin** [jibrelnetwork/jwallet-web#182]
On the screenshot below we can see two errors:
- JNT is displayed as a licensed token, but it is not
- JNT transfer is not allowed, but actually, it is allowed for all people

![image](https://user-images.githubusercontent.com/2777812/35773123-ea14a352-0959-11e8-98ff-3bc93115d5b5.png)

Let's fix this.
As I understand it should be enough just to mark JNT as not a licensed token

**Comment by IViol** [comment]
Fixed in bac872731f2099caec9e26810c796d1930c13288
