### ISSUE TITLE
Users unable to send transactions

### ISSUE THREAD

**Issue by mezrin** [jibrelnetwork/jwallet-web#184]
Example address: https://etherscan.io/address/0x5fb1f4e71f116a9ac996835d9d6aac49da74999c

Users try to send funds (ETH/JNT) and get errors like this:
![image](https://user-images.githubusercontent.com/2777812/35823269-088c80b8-0ac0-11e8-9d33-c8c28f9da3bd.png)

We need to figure out what was the reason of that bug.
And need to make error messages more clear for the user.

**Comment by IViol** [comment]
(perhaps) resolved by https://github.com/jibrelnetwork/jwallet-web/pull/185

**Comment by IViol** [comment]
Resolved by https://github.com/jibrelnetwork/jwallet-web/pull/190
