### ISSUE TITLE
Clear keystore entirely

### ISSUE THREAD

**Issue by mezrin** [jibrelnetwork/jwallet-web#186]
We have a significant feature request - clear all keystore entirely
Sometimes people want to clear all keystore
Sometimes people forget password and have to reset it (right now they have to manually clean up browser data)

In such clean-up we need to delete all data of the app: keystore, tx data etc.

Need to add it to the old design because many users requested this
We will have the same feature in the new design, so this is not a big wasting of time

We can add a new element to the menu of the keystore:
- user clicks element `Clear keys`
- Simple confirmation yes/no
- Clear all data
- redirect to the root path of the app

![image](https://user-images.githubusercontent.com/2777812/35884245-1c48894a-0b9b-11e8-8615-ee72558869e4.png)

**Comment by mezrin** [comment]
https://jibrelnetwork.freshdesk.com/a/tickets/1933

**Comment by IViol** [comment]
Resolved by https://github.com/jibrelnetwork/jwallet-web/pull/187
