### ISSUE TITLE
Asset picker component

### ISSUE THREAD

**Issue by erohin** [jibrelnetwork/jwallet-web#194]
**Closed**
![image](https://user-images.githubusercontent.com/2608959/36314709-b5bccd90-1346-11e8-8b21-62d78397025f.png)

**Opened**
![image](https://user-images.githubusercontent.com/2608959/36314696-aa567de8-1346-11e8-85eb-a41c886dec96.png)

**Comment by IViol** [comment]
Updates required:
- styles of selected item (blue on active, chevron icon, etc)
- asset icons
- custom scrollbar

**Comment by IViol** [comment]
#301
