### ISSUE TITLE
ETH balance shows as 0 incorrectly, blocking transfer

### ISSUE THREAD

**Issue by tarekayna** [jibrelnetwork/jwallet-web#199]
My address has 1.7 ETH. jWallet shows it has 0 ETH. As a result I can't send out ETH from the wallet.

![image](https://user-images.githubusercontent.com/1313626/36470955-665f4b4e-16f5-11e8-839b-f97c90d24209.png)

Address on etherscan: https://etherscan.io/address/0x3a044f41cbc6c26beeb6e7ffd8dab54282118053

![image](https://user-images.githubusercontent.com/1313626/36470982-812706ba-16f5-11e8-8532-4468d77625f0.png)

**Comment by IViol** [comment]
Hello, our main Ethereum node was down for some time. Now it should be ok, can you please try again?
Re-open the issue if you still have such problem.
