### ISSUE TITLE
Paginator component

### ISSUE THREAD

**Issue by erohin** [jibrelnetwork/jwallet-web#207]
![image](https://user-images.githubusercontent.com/2608959/36539982-afa1f19a-17e9-11e8-92b8-6f6f62934844.png)

**Comment by martinin** [comment]
@erohin а этот пагинатор был только в старой версии, для хелпа. В новой его нет. Или это что-то другое?

**Comment by erohin** [comment]
@martinin Да, это из старой версии, мы его в работу взяли еще когда дизайн был в Adobe XD, и сейчас не смогли найти его цеплине. На будущее нужно придумать какой-то механизм, по отмене/подтверждению задач при изменениях в дизайне, так как сейчас об этих изменениях мы можем узнать если только полностью сравним вручную две версии дизайна.

**Comment by martinin** [comment]
@erohin ну сейчас все макеты точно в актуальном состоянии. Наверно тогда надо снести задачу.
