### ISSUE TITLE
Component JInput

### ISSUE THREAD

**Issue by IViol** [jibrelnetwork/jwallet-web#224]
![screenshot from 2018-03-05 16-14-03](https://user-images.githubusercontent.com/11073017/36980200-b01647a2-209a-11e8-8cdc-30bbbebc7cc5.png)
props:
- onValueChange (function)
- name (i18n)
- value (string)
- placeholder (i18n)
- errorMessage (string)
- successMessage (string)
- editable (bool)
- multiline (bool)

If successMessage.length > 0 - show checkmark.
If errorMessage.length > 0 - show errorMessage.

**Comment by erohin** [comment]
**States:**
Disabled state: `?` (appearance)
Multiline: `?` (appearance)
Error message: `?` (appearance)
Success message: `?` (appearance)

**Comment by martinin** [comment]
Disabled state: ? Zeplin
Multiline: ? Nope
Error message: ? Zeplin
Success message: ? Nope

https://app.zeplin.io/project/5aafafbd88066fa620959ee3/screen/5aafdfa4508f1e7a6778ce74

**Comment by erohin** [comment]
**Multiline view**
![image](https://user-images.githubusercontent.com/2608959/38025430-063d41f0-3291-11e8-9744-25cb9c05734e.png)
https://zpl.io/aBOkZLO
