### ISSUE TITLE
Component IconButton

### ISSUE THREAD

**Issue by IViol** [jibrelnetwork/jwallet-web#226]
![screenshot from 2018-03-05 16-48-02](https://user-images.githubusercontent.com/11073017/36980419-4685a3ae-209b-11e8-9f79-3286b96a8eb5.png)
![screenshot from 2018-03-05 16-48-15](https://user-images.githubusercontent.com/11073017/36980424-4915002e-209b-11e8-9315-1428ee64c3b9.png)
The same as #223 
But there is `icon` prop instead of `label` prop.

**Comment by erohin** [comment]
#223
