### ISSUE TITLE
Component RadioButton

### ISSUE THREAD

**Issue by IViol** [jibrelnetwork/jwallet-web#227]
![screenshot from 2018-03-05 16-53-23](https://user-images.githubusercontent.com/11073017/36980813-7a18e504-209c-11e8-9f19-d12c87a58226.png)
props:
- toggle (function)
- label/children (node)
- isActive (bool)

**Prototype**: [RadioGroup](http://blueprintjs.com/docs/v2/#core/components/forms/radio)

**Comment by erohin** [comment]
![image](https://user-images.githubusercontent.com/2608959/37597502-b56efc52-2b90-11e8-83ae-4764e369d45f.png)
'Use custom path' option behavior: `?`

**Comment by martinin** [comment]
All states - https://app.zeplin.io/project/5aafafbd88066fa620959ee3/screen/5aafdfa4d53e10386f6aeba9

**Comment by martinin** [comment]
https://app.zeplin.io/project/5aafafbd88066fa620959ee3/screen/5aafdfa4d53e10386f6aeba9

Use custom path - behavior like input type text.
