### ISSUE TITLE
Component PasswordInput

### ISSUE THREAD

**Issue by IViol** [jibrelnetwork/jwallet-web#228]
![screenshot from 2018-03-05 16-25-21](https://user-images.githubusercontent.com/11073017/36980905-b72ad060-209c-11e8-8d5a-fe847108c136.png)
Based on #224 
\+ props:
- passwordStatus (string) - info about password strength.

**Comment by erohin** [comment]
UX

**Comment by erohin** [comment]
Password status samples: `?` (text and appearance)
Checkmark status: `?` (when checkmark is shown)

**Comment by martinin** [comment]
Statuses, errors etc like an old wallet.
Zeplin - https://app.zeplin.io/project/5aafafbd88066fa620959ee3/screen/5aafdfa415cdc17748b94576
