### ISSUE TITLE
Migration of localStorage data

### ISSUE THREAD

**Issue by mezrin** [jibrelnetwork/jwallet-web#249]
We reworked format of localStorage data
Need to implement migrations
My suggestions:
- [ ] implement auto-migration of old key-store to the new key-stores
- [ ] add version prefixes for the new keys for data like transactions, balances, etc. (in order not to mix with the old data)

**Comment by IViol** [comment]
Migration from old keystore data format already implemented [here](https://github.com/jibrelnetwork/jwallet-web-keystore/blob/master/src/migrations.js#L3)
