### ISSUE TITLE
Rework display of "no data"

### ISSUE THREAD

**Issue by mezrin** [jibrelnetwork/jwallet-web#278]
![image](https://user-images.githubusercontent.com/2777812/37978709-51965134-31ef-11e8-96a7-f9dbcab3c287.png)

**Comment by martinin** [comment]
@erohin а это когда ошибочные данные вернулись? Или точнее вообще ничего не вернулось.

**Comment by erohin** [comment]
@martinin Тут нужно показать ситуацию, когда нода не ответила и нужно как-то сообщить пользователю об этом, так как текущие данные (которые были до запроса) возможно устарели.
