### ISSUE TITLE
Zoom in browser

### ISSUE THREAD

**Issue by mezrin** [jibrelnetwork/jwallet-web#279]
Google chrome 80%

![image](https://user-images.githubusercontent.com/2777812/37978785-892b9fa0-31ef-11e8-9464-14ca8e891f0e.png)

**Comment by IViol** [comment]
This glitch disappears on reload of page. It is the problem of external library that we use for custom scrollbar.
We can implement our own one, but at the moment it is overhead (issue is reproduced when scale of browser window only).

@mezrin I think we should mark this as `pending`.

**Comment by mezrin** [comment]
@IViol agreed
