### ISSUE TITLE
Change of the Etherscan Testnet API service URL Endpoints 

### ISSUE THREAD

**Issue by alekseyselikhov** [jibrelnetwork/jwallet-web#284]
The Etherscan Testnet API service URL Endpoints have been updated.
See [link](https://etherscancom.freshdesk.com/support/solutions/articles/35000051806-change-of-testnet-api-service-endpoint-url)
The previous (old)  API endpoints will cease to function after March 31, 2018. There are NO changes to the Mainnet API end points

**Comment by IViol** [comment]
4e7724f26c3ec45f0923aeaee1e52758be8c33b0
