### ISSUE TITLE
Add ability to go to previous step in Create/Import modals

### ISSUE THREAD

**Issue by IViol** [jibrelnetwork/jwallet-web#55]
Currently it is impossible, and user must reload page and go from the start.

**Comment by IViol** [comment]
It is needed, for example, for such case:
- user imports the same address (or another type of account), that has already exist in keystore
- keystore library will not allow this import, but error about that will be shown only on input password step (in appropriate popup)
- user can't go to previous step to import another address (or maybe just change derivation path for mnemonic)

I see two ways to resolve:
- do all checks like this on correspond steps. For that we need to exspose them from keystore library.
- add ability to go to previous step in modals

**Comment by mezrin** [comment]
Will be implemented in the new design
